apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-deployment-vs
spec:
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal-vs
        image: drupal:latest
        env:
        - name: DRUPAL_DB_HOST
          value: "mysql-service-vs"
        - name: DRUPAL_DB_NAME
          value: "drupal"
        - name: DRUPAL_DB_USER
          value: "vs"
        - name: DRUPAL_DB_PASSWORD
          value: "vs"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: drupal-data-vs
          mountPath: /var/www/html/sites/default/files #Montamos en un subdirectorio para la persistencia de datos.
      volumes:
      - name: drupal-data-vs
        persistentVolumeClaim:
          claimName: drupal-pvc