apiVersion: v1
kind: Service
metadata:
  name: mysql-service-vs
spec:
  type: ClusterIP #Limito el acceso de MYSQL solo a que este dentro del cluster.
  ports:
    - name: mysql
      port: 3306
  selector:
    app: mysql
