apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-vs
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "example"
        - name: MYSQL_DATABASE
          value: "drupal"
        - name: MYSQL_USER
          value: "vs"
        - name: MYSQL_PASSWORD
          value: "vs"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data-vs
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data-vs
        persistentVolumeClaim:
          claimName: mysql-pvc

